- package-lock.json
- package.json
- src/server/server.ts
We need this so client-side applications can use the GraphQL endpoint directly.
> Enable CORS

- src/server/resolvers.ts
This was the old behaviour, which we should keep for now.
We may later switch to identifiers (#17) but should do so consistently throughout the app.
> Expose dataset identifier rather than IRI

- README.md
- package-lock.json
- package.json
- src/commands/sources/list.ts
- src/commands/sources/query.ts
- src/server/resolvers.ts
- src/server/schema.ts
- src/services/distributions.ts
- src/services/query.ts
- tsconfig.json
* Fix #17.
* Adapt to https://github.com/netwerk-digitaal-erfgoed/network-of-terms-catalog/pull/9.
* Replace dataset identifier with distribution IRI in both code and docs.
> Upgrade network-of-terms-catalog to 2.0.0

- src/server/server.ts
Currently, / shows a 404, so redirect to /playground to give
users a meaningful homepage.
> Redirect / to /playground

- .github/workflows/deploy.yml
* GHCR is replacing GitHub Packages for Docker images.
* This enables us to make the image public.
* Rename Docker image to network-of-terms-api.
> Migrate to GitHub Container Registry (GHCR)

- src/services/query.ts
Fix #34.
@ddeboer This is a first shot at [34](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-api/issues/34) and open to debate.
Some background:
1. The issue is indeed caused by `Promise.all()`.
2. We could fix it with `Promise.allSettled()`, i.e. by removing the source that failed and continuing with the sources that succeeded. However, this way the user doesn't get to see the failed source in the response (e.g. GraphQL output), which is somewhat strange: if I query two sources and one of these fails, I still would like to see that source in the response (otherwise it suggests that the failed source wasn't queried at all).
3. The PR ensures that all sources resolve, even if one of these failed (in which case an empty result set is returned). We could improve this by also …
> fix: resolve source errors

- README.md
- src/commands/sources/query.ts
- src/server/resolvers.ts
- src/server/schema.ts
- src/services/distributions.ts
- src/services/query.ts
* Fix #52.
* Add two error classes: `ServerError` (which we already use)
and `TimeoutError` (which we can start using when we support
timeouts).
* Deprecate `terms` but don’t remove it yet to prevent BC breaks.
Recommend `result` instead.
> feat: Return errors

- src/services/query.ts
Extended the sorting of the results to include the altLabels. This is helpful when many prefLabels have the same value f.g. searching for 'markt' in Wikidata streets.
> Feat: extended sorting

- src/services/query.ts
```
TypeError [ERR_INVALID_ARG_TYPE]: The \"url\" argument must be of type
string. Received an instance of IRI"}
```
> fix: URL type error

- src/commands/sources/query.ts
- src/server/resolvers.ts
- src/server/schema.ts
- src/services/distributions.ts
- src/services/query.ts
* Fix #45.
* Use `Promise.race` to set a timeout on each outgoing request.
* Configurable through `DEFAULT_QUERY_TIMEOUT` and `MAX_QUERY_TIMEOUT`
env vars; respectively 5 and 10 sec.
> feat: Add query timeout

- README.md
- src/server/server.ts
The playground was removed in Mercurius 8.0
(https://github.com/mercurius-js/mercurius/pull/453). Instead, Mercurius
ships with GraphiQL, so enable that.
> Replace GraphQL playground

- packages/network-of-terms-graphql/test/server.test.ts
- packages/network-of-terms-query/src/index.ts
- packages/network-of-terms-reconciliation/test/server.test.ts
server-test.ts has dependencies on libraries that are available only in
dev (such as jest-dev-server), so it must not be imported by
network-of-terms-query's index.ts.
Remove that import and replace it in the tests with a relative include.
> fix: Remove dev-only dependency

- .npmrc
* Enable engine strict to prevent installing dependencies when Node
version does not match `engine`.
* Use `engine-strict` in `.npmrc` because the `engineStrict` option in
`package.json` is ignored.
> chore: Enforce Node version

- package-lock.json
- packages/network-of-terms-cli/README.md
- packages/network-of-terms-cli/package.json
- packages/network-of-terms-cli/src/list.ts
- packages/network-of-terms-cli/src/query.ts
* Update instructions in readme.
* Remove dependency on deprecated `@oclif/command`.
* Remove explicit dependency on `rdf-js` because it's not needed.
* Reduce function visibility.
> fix: Update CLI

- .github/workflows/deploy.yml
If the service cannot be started, we want to know as soon as possible.
> build: Add timeout to fail deployment

- jest.config.js
- packages/network-of-terms-catalog/catalog/datasets/gtaa-classificatie.jsonld
- packages/network-of-terms-catalog/catalog/datasets/gtaa-genres.jsonld
- packages/network-of-terms-catalog/catalog/datasets/gtaa-geografische-namen.jsonld
- packages/network-of-terms-catalog/catalog/datasets/gtaa-namen.jsonld
- packages/network-of-terms-catalog/catalog/datasets/gtaa-onderwerpen-beng.jsonld
- packages/network-of-terms-catalog/catalog/datasets/gtaa-onderwerpen.jsonld
- packages/network-of-terms-catalog/catalog/datasets/gtaa-persoonsnamen.jsonld
- packages/network-of-terms-catalog/src/catalog.ts
- packages/network-of-terms-catalog/test/catalog.test.ts
- packages/network-of-terms-catalog/test/fixtures/credentials.jsonld
* Substitute variables (`$DATASET_CREDENTIALS`) in `contentUrl` with
value from environment variable.
* If no corresponding environment variable is found, substitute with
empty string.
Fix #478.
> feat: Support source authentication

- packages/network-of-terms-catalog/catalog/queries/search/gtaa-persoonsnamen.rq
Query for the GTAA persoonsnamen can take quite a while because of the size of the term source (>200k). Therefore, the query was defined so that it would only allow single word source. Also, the number of result concepts was limited to 10. So I thought. It turned out the limit was on triples, because of the CONSTRUCT query type. Now the limit is raised to 50, so that it will return some 10 concepts when found. Still, whenever a term is searched that is very unique and 50 triples aren't produced, the whole dataset is being searched and timeouts can happen.
> optimized query for gtaa persoonsnamen

- .github/workflows/deploy.yml
* GitHub Actions does not support arch64 natively yet 
(https://github.com/actions/virtual-environments/issues/2187), so we need QEMU.
* QEMU slows down our builds too much: from ~2 min to ~11 min.
* Revert "feat: Build multi-arch Docker image (#568)"
* Revert "build: Enable QEMU support for multi-arch builds"
> build: Revert multi-arch Docker images

- jest.config.js
- packages/network-of-terms-query/test/fixtures/terms.ttl
- packages/network-of-terms-reconciliation/src/score.ts
- packages/network-of-terms-reconciliation/test/server.test.ts
Previously, we calculated a combined score per set of prefLabels and set
of altLabels and took the max between the two.
Change this to calculate score for each of the individual prefLabels and
altLabels.
> fix: Calculate score per individual term

- jest.config.js
- package-lock.json
- packages/network-of-terms-reconciliation/package.json
- packages/network-of-terms-reconciliation/src/score.ts
- packages/network-of-terms-reconciliation/test/score.test.ts
- packages/network-of-terms-reconciliation/test/server.test.ts
* Use cosine similarity instead of Levenshtein to ignore differences in
word order.
* Ignore punctuation marks.
Fix #580.
> feat: Improve reconciliation scoring

- packages/network-of-terms-catalog/catalog/queries/search/wikidata-entities-streets.rq
* ‘Schoolstraat Nijmegen’ returned no matches, whereas ‘Schoolstraat’ didn’t
include Schoolstraat in Nijmegen due to the LIMIT on the results.
* Replace `mwapi:search` with `mwapi:srsearch`, which seems more capable.
* Simplify CONSTRUCT.
* Only construct altLabel manually if the result doesn’t already come with an
an altLabel. This prevents duplicate altLabels ‘Street (City), Street (City)’.
> fix: Improve Wikidata streets search

- jest.config.js
- packages/network-of-terms-catalog/catalog/queries/lookup/brinkman-nta-stcn.rq
- packages/network-of-terms-catalog/catalog/queries/lookup/gtaa.rq
- packages/network-of-terms-query/src/catalog.ts
- packages/network-of-terms-query/src/lookup/lookup.ts
- packages/network-of-terms-query/src/server-test.ts
- packages/network-of-terms-query/src/terms.ts
* Queries can return a `skos:inScheme` triple that will be used
instead of the dataset matching the URI prefix.
Fix #492.
Fix #604.
> fix: Return correct source when sources share URI prefix

- packages/network-of-terms-catalog/catalog/datasets/brabantse-gebouwen.jsonld
- packages/network-of-terms-catalog/catalog/publishers.jsonld
- packages/network-of-terms-catalog/catalog/queries/lookup/brabantse-gebouwen.rq
- packages/network-of-terms-catalog/catalog/queries/search/brabantse-gebouwen.rq
This PR proposes a new terminology source: 'Brabantse gebouwen' from Erfgoed Brabant. The source currently only contains monasteries; types such as churches and chapels are going to be added in the near future.
> feat: Add source ‘Brabantse gebouwen’

- packages/network-of-terms-catalog/catalog/queries/lookup/muziekschatten.rq
- packages/network-of-terms-catalog/catalog/queries/search/muziekschatten-personen.rq
Apparently STRLEN() rather than BOUND() is needed here.
> fix: Blank names returned from Muziekschatten

- packages/network-of-terms-catalog/catalog/queries/lookup/muziekschatten.rq
* And don't require Dutch language names for persons.
> fix: Differentiate between datasets in Muziekschatten lookup

- packages/network-of-terms-catalog/catalog/queries/search/gtaa.rq
- performance is improved, for large GTAA conceptschemes like Persoonsnamen.
- diacritics are handled
- separate query `gtaa-persoonsname.rq` can be removed.
> fulltext querying enable in jena to increase preformance

- packages/network-of-terms-catalog/catalog/datasets/geonames.jsonld
- packages/network-of-terms-catalog/catalog/queries/search/geonames.rq
Changed the description for the Geonames source to show the German data is now included. Also changed to search query to use STRSTARTS in stead of CONTAINS to reduce the noise.
> Feat: geonames update

- packages/network-of-terms-catalog/catalog/queries/search/gtaa.rq
Search on GTAA sources is not working due to a change on the triple store. 
To fix this: Small change that replaces the justskos prefix with openskos.
> replace justskos namespace

- packages/network-of-terms-catalog/catalog/datasets/cht-materials.jsonld
- packages/network-of-terms-catalog/catalog/datasets/cht-styles-and-periods.jsonld
- packages/network-of-terms-catalog/catalog/queries/search/cht-materials.rq
- packages/network-of-terms-catalog/catalog/queries/search/cht-styles-and-periods.rq
Added two new CHT fragments as sources based on the 'materials' and the 'styles and periods' hierarchy.
Fix #854
> feat: Split CHT

- packages/network-of-terms-catalog/catalog/queries/search/gtaa.rq
The namespace for the B&G properties is now published and the queries need to use it to work.
Also, the LIMIT was still on 1000, which seemed appropriate when the query seemed to limit the number of triples in the construct query. Now we have changed the query to use the full text capabilities, the LIMIT seems to be the number of concepts. Note that the Jena results are not ranked, but when the limit is set to 10, the 10 most relevant results are returned (although unordered). When using a limit 1000 the best result may end up on place 1000 in the worst case.
We use the Apache Lucene full text engine on Apache Jena triple store. This is able to send relevance information, which can be used to sort the results. Currently, the network of terms is not using such functionality. We could …
> replaced namespace and decreased limit

- CONTRIBUTING.md
- jest.config.js
- packages/network-of-terms-catalog/README.md
- packages/network-of-terms-catalog/catalog/queries/search/gtaa.rq
- packages/network-of-terms-graphql/test/server.test.ts
- packages/network-of-terms-query/src/query.ts
- packages/network-of-terms-query/src/terms.ts
- packages/network-of-terms-query/test/fixtures/terms.ttl
* Queries may sort by relevance score.
* If they do, sort by score primarily. For identical scores, fall back to alphabetical sort.
* If they do not, only sort alphabetically.
* This PR does not yet expose the score in the GraphQL API.
Fix #537
> feat: Sort by relevance score if available

- packages/network-of-terms-catalog/catalog/queries/lookup/brabantse-gebouwen.rq
- packages/network-of-terms-catalog/catalog/queries/search/brabantse-gebouwen.rq
refactor(brabantse-gebouwen.rq): replace skos:altLabel with skos:hiddenLabel and simplify skos:scopeNote
refactor(brabantse-gebouwen.rq): remove buildingTypeScopeNote and addressScopeNote, add hiddenLabel and scopeNote to CONSTRUCT
The queries have been simplified because the information is now available in the source endpoint.
> Update SPARQL lookup and search query for brabantse-gebouwen

- packages/network-of-terms-reconciliation/src/server.ts
Reconciliation services (e.g. https://termennetwerk-api.netwerkdigitaalerfgoed.nl/reconcile/https://demo.netwerkdigitaalerfgoed.nl/geonames)
show HTTP instead of HTTPS as the protocol.
This is probably because the Forwarded/X-Forwarded-Proto
headers set by our reverse proxy are not trusted by Fastify by default.
> fix: Trust Forwarded headers for getting protocol

- packages/network-of-terms-graphql/README.md
- packages/network-of-terms-query/src/query.ts
For example
https://termennetwerk.netwerkdigitaalerfgoed.nl/?q=dorp\&datasets=https://query.wikidata.org/sparql%23entities-streets
needs longer than our current max timeout of 10 sec.
> feat: Raise max query timeout

- jest.config.js
- packages/network-of-terms-query/src/instrumentation.ts
While I prefer an exponential histogram because it manages buckets
automatically, it causes the OpenTelemetry collector to throw
`failed to translate metric`.
Because the default bucket sizes have been fixed in sdk-metrics 1.15.0,
they have become useful enough to just use them: https://github.com/open-telemetry/opentelemetry-js/pull/3893/ 
Compare https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13443
> fix: Failed to translate metric

- packages/network-of-terms-catalog/catalog/datasets/muziekschatten-onderwerpen.jsonld
- packages/network-of-terms-catalog/catalog/datasets/muziekschatten-personen.jsonld
- packages/network-of-terms-catalog/catalog/queries/lookup/muziekschatten.rq
- packages/network-of-terms-catalog/catalog/queries/search/muziekschatten-onderwerpen.rq
- packages/network-of-terms-catalog/catalog/queries/search/muziekschatten-personen.rq
Muziekschatten has switched to https://, so update our
references.
> feat: Update Muziekschatten namespace

- packages/network-of-terms-catalog/catalog/queries/search/geonames.rq
> feat: Sort GeoNames by relevance score

- docker-compose.yml
This reverts commit ba7ebdeb5ef7a1e6a27677b20899d8f6e93b0e31.
These ports should not be needed when running the tests in Docker.
Note that #1048 was solved differently, in #1050.
Fix #1068
> revert: "test: Fix tests when run in Docker container (#1049)"

- jest.config.js
- package.json
- packages/network-of-terms-catalog/catalog/queries/search/adamlink-straten.rq
- packages/network-of-terms-catalog/catalog/queries/search/brinkman.rq
- packages/network-of-terms-catalog/catalog/queries/search/muziekschatten-onderwerpen.rq
- packages/network-of-terms-catalog/catalog/queries/search/muziekschatten-personen.rq
- packages/network-of-terms-catalog/catalog/queries/search/mw-genresstijlen.rq
- packages/network-of-terms-catalog/catalog/queries/search/mw-personengroepen.rq
- packages/network-of-terms-catalog/catalog/queries/search/nmvw.rq
- packages/network-of-terms-catalog/catalog/queries/search/nta.rq
- packages/network-of-terms-catalog/catalog/queries/search/rkdartists.rq
- packages/network-of-terms-graphql/README.md
- packages/network-of-terms-graphql/src/schema.ts
- packages/network-of-terms-query/src/search/query-mode.ts
BREAKING CHANGE: `queryMode: DEPRECATED` was removed. Default is now
`queryMode: OPTIMIZED`.
Fix #1058
> feat: Remove deprecated query mode

- packages/network-of-terms-catalog/catalog/queries/lookup/goudatijdmachine-straten.rq
- packages/network-of-terms-catalog/catalog/queries/search/goudatijdmachine-straten.rq
Adjusted queries to use the new GTM ontology (more schema.org) and to make use of a Lucene-index.
> Gouda Tijdmachine query update

- packages/network-of-terms-catalog/catalog/queries/lookup/aat.rq
- packages/network-of-terms-catalog/catalog/queries/search/aat-materials.rq
- packages/network-of-terms-catalog/catalog/queries/search/aat-processes-and-techniques.rq
- packages/network-of-terms-catalog/catalog/queries/search/aat-styles-and-periods.rq
* Support exactMatches without label.
* Filter out self-references.
> fix: AAT exactMatch has no labels

- packages/network-of-terms-catalog/catalog/datasets/cht.jsonld
- packages/network-of-terms-catalog/catalog/queries/lookup/cht.rq
- packages/network-of-terms-catalog/catalog/queries/search/cht-styles-and-periods.rq
- packages/network-of-terms-catalog/catalog/queries/search/cht.rq
* Duplicate generate PoolParty queries to make CHT-specific changes.
> feat: Exclude RCE referentienetwerk matches from CHT

- packages/network-of-terms-catalog/catalog/datasets/adamlink-adressen.jsonld
- packages/network-of-terms-catalog/catalog/datasets/adamlink-straten.jsonld
- packages/network-of-terms-catalog/catalog/publishers.jsonld
- packages/network-of-terms-catalog/catalog/queries/lookup/adamlink-adressen.rq
- packages/network-of-terms-catalog/catalog/queries/lookup/adamlink-straten.rq
- packages/network-of-terms-catalog/catalog/queries/search/adamlink-adressen.rq
- packages/network-of-terms-catalog/catalog/queries/search/adamlink-straten.rq
This PR:
1. Updates the Adamlink Streets dataset to the latest version hosted at https://lod.uba.uva.nl/ATM/Adamlink.
2. Adds the Adamlink Historical Addresses as separate dataset. 
The search and lookup queries for both datasets use the generic Amsterdam Time Machine Knowledge Graph endpoint at https://api.lod.uba.uva.nl/datasets/ATM/ATM-KG/services/ATM-KG/sparql (Virtuoso).
> Update and add Adamlink resources

- jest.config.js
- package-lock.json
- package.json
- packages/network-of-terms-catalog/package.json
- packages/network-of-terms-catalog/src/genre.ts
- packages/network-of-terms-catalog/src/index.ts
- packages/network-of-terms-catalog/test/catalog.test.ts
- packages/network-of-terms-catalog/test/shacl.test.ts
- packages/network-of-terms-graphql/README.md
- packages/network-of-terms-graphql/src/resolvers.ts
- packages/network-of-terms-graphql/src/schema.ts
- packages/network-of-terms-graphql/test/server.test.ts
- packages/network-of-terms-query/src/helpers/logger.ts
- packages/network-of-terms-query/src/query.ts
- packages/network-of-terms-query/test/query.test.ts
- packages/network-of-terms-query/test/search/query-mode.test.ts
- packages/network-of-terms-reconciliation/test/score.test.ts
- packages/network-of-terms-reconciliation/test/server.test.ts
- tsconfig.build.json
* Switch to module `nodenext` to be able to import the memoize library.
* Replace ts-jest with @swc/jest to fix test build.
> feat: Add genres to GraphQL API

- packages/network-of-terms-catalog/catalog/queries/search/goudatijdmachine-straten.rq
Following [De terminologiebron publiceert relaties met termen in andere terminologiebronnen](https://netwerk-digitaal-erfgoed.github.io/requirements-terminologiebronnen/#6) the Gouda Time Machine links the streets to other thesauri. These links to the same term in other thesauri weren't included in the `skos:exactMatch` part of the query. This PR fixes that omission.  
Test case: search for ["Raam" in "Goudse straten"](https://termennetwerk.netwerkdigitaalerfgoed.nl/?q=raam&datasets=https://www.goudatijdmachine.nl/id/straten%23streets) and see links in results to BAG and WikiData.
> updated query to better show the relations to other thesauri (skos:exactMatch)

- packages/network-of-terms-catalog/catalog/datasets/rijksmonumenten.jsonld
- packages/network-of-terms-catalog/catalog/queries/lookup/rijksmonumenten.rq
- packages/network-of-terms-catalog/catalog/queries/search/rijksmonumenten.rq
RCE Rijksmonumenten now uses the CHO dataset (more stable and up-to-date). Endpoint is changed and queries as well, since CHO uses a different datamodel.
> Update of Rijksmonumenten dataset and queries

- packages/network-of-terms-catalog/catalog/datasets/nmvw.jsonld
Switch Wereldculturen thesaurus endpoint from NDE to colonialcollections
As requested by @GertjanFi and @sdevalk
> NMVW to new endpoint

- packages/network-of-terms-catalog/catalog/datasets/rkdartists.jsonld
- packages/network-of-terms-catalog/catalog/queries/lookup/rkdartists.rq
- packages/network-of-terms-catalog/catalog/queries/search/rkdartists.rq
> feat: Move to RKD endpoint

- packages/network-of-terms-catalog/catalog/queries/search/wikidata-entities-streets.rq
Test case: ‘Grote Markt Haarlem’.
Fix #1427
> feat: Include Wikidata main squares

- packages/network-of-terms-catalog/catalog/queries/search/goudatijdmachine-straten.rq
PIDs in the GTM KG used to be in the sdo:identifier property, but have moved to the owl:sameAs property, this made the ETL pipeline much easier.
> fix: goudse straten - pid property change

- jest.config.js
Node 22, recently promoted to LTS, reports incorrect code coverage:
https://github.com/nodejs/node/issues/51251.
The simplest solution for now is just to update our threshold to
Node 22’s reported coverage level.
> test: Fix code coverage on Node 22

- packages/network-of-terms-catalog/catalog/queries/search/poolparty.rq
The Poolparty search query now returns concepts of type
`<http://schema.semantic-web.at/ppt/suggested#Concept>`,
brought to light by the new PiCoT thesaurus. We probably want
to return only published Concepts, so filter by that.
> fix: Filter by skos:Concept in Poolparty sources

- .github/workflows/qa.yml
- .github/workflows/release.yml
- package.json
`npm --workspaces` always returns 0, even if the command fails 
for any of the workspaces: https://github.com/npm/rfcs/issues/575.
Work around this by running the command on each workspace individually.
> build: Fail build on compilation error

- packages/network-of-terms-catalog/catalog/datasets/brinkman.jsonld
- packages/network-of-terms-catalog/catalog/datasets/nta.jsonld
- packages/network-of-terms-catalog/catalog/datasets/stcn-drukkers.jsonld
SPARQL endpoint now serviced by TriplyDB (with Virtuoso service to retain <bif:contains> functionality). 
contentUrl was http but always redirected to https, so changed that too.
> Change SPARQL endpoints KB sources

- jest.config.js
- packages/network-of-terms-catalog/catalog/queries/lookup/geonames.rq
- packages/network-of-terms-catalog/catalog/queries/search/geonames.rq
- packages/network-of-terms-catalog/test/catalog.test.ts
- packages/network-of-terms-graphql/src/resolvers.ts
- packages/network-of-terms-graphql/src/schema.ts
- packages/network-of-terms-graphql/src/server.ts
- packages/network-of-terms-graphql/test/server.test.ts
- packages/network-of-terms-query/src/catalog.ts
- packages/network-of-terms-query/src/server-test.ts
- packages/network-of-terms-query/test/fixtures/terms.ttl
- packages/network-of-terms-reconciliation/src/data-extension.ts
- packages/network-of-terms-reconciliation/src/preview.ts
- packages/network-of-terms-reconciliation/src/query.ts
- packages/network-of-terms-reconciliation/src/server.ts
- packages/network-of-terms-reconciliation/test/server.test.ts
* Filter reconciliation queries by single language.
* Add `languages` GraphQL query argument. If passed, results are
returned as language/value-tagged strings instead of plain strings.
* If that `languages` argument is passed, the first language 
becomes the catalog language. If not, fall back to the `Accept-Language`
header.
* Define languages as enum in GraphQL schema and base its values
on the languages provided in the catalog’s datasets.
Ref #1410
> feat: Support multilingual search queries

- jest.config.js
- packages/network-of-terms-catalog/src/getCatalog.ts
- packages/network-of-terms-catalog/test/catalog.test.ts
- packages/network-of-terms-cli/src/query.ts
- packages/network-of-terms-graphql/src/resolvers.ts
- packages/network-of-terms-graphql/test/server.test.ts
- packages/network-of-terms-query/src/catalog.ts
- packages/network-of-terms-query/src/distributions.ts
- packages/network-of-terms-query/src/lookup/lookup.ts
- packages/network-of-terms-query/src/server-test.ts
- packages/network-of-terms-query/test/query.test.ts
- packages/network-of-terms-reconciliation/src/server.ts
* Replace the IRI class, which extended URL, with a simple type as alias for string.
Ref netwerk-digitaal-erfgoed/dataset-knowledge-graph#145
BREAKING CHANGE: all URIs are now typed IRI, an alias for string.
> fix: Preserve dataset URIs
