- .github/workflows/docker.yml
> Publish Docker image to GitHub Packages

- src/services/query.ts
* Fix #14.
* Fix #19.
* Fix #20.
This reverts commit 65ec9176a98ad50454492ac06d100e2fc560161e.
> Revert "Fix multi-word term queries by quoting bif:contains argument"

- src/commands/sources/query.ts
- src/server/resolvers.ts
- src/server/server.ts
- src/services/distributions.ts
- src/services/query.ts
Fix netwerk-digitaal-erfgoed/bruikbaar#31.
> Share single Comunica instance

- README.md
- package-lock.json
- package.json
- src/server/resolvers.ts
- src/server/schema.ts
* Upgrade network-of-terms-catalog to 3.0.0.
* Replace identifier with name/alternateName.
> Add dataset and creator alternate names

- .github/workflows/qa.yml
Add simple QA GitHub Action. We have no tests yet, but we can at
least lint and compile.
> Add QA action

- .github/workflows/update-catalog.yml
Ref netwerk-digitaal-erfgoed/network-of-terms-catalog#24.
> build: Automatically update catalog

- package-lock.json
- package.json
Update the Network of Terms catalog.
> feat: Bump network-of-terms-catalog

- README.md
- src/server/resolvers.ts
- src/server/schema.ts
- src/services/terms.ts
> feat: Return skos:related terms

- src/services/query.ts
> feat: Sort results alphabetically by prefLabel

- src/services/terms.ts
Fix #143.
This is a result of #36.
> fix: Guard against incomplete related terms

- package-lock.json
- package.json
> Downgrade Comunica to work around Content-Length bug

- src/services/terms.ts
> fix: Handle duplicate term URIs

- src/services/terms.ts
> fix: support SKOS 2008 in type check

- codemeta.json
> feat: Add CodeMeta metadata

- README.md
- jest.config.js
- src/server/resolvers.ts
- src/server/schema.ts
- src/services/terms.ts
- test/fixtures/terms.ttl
- test/server/server.test.ts
> Return seeAlso URIs

- jest.config.js
- package-lock.json
- package.json
- src/main.ts
- src/reconciliation/manifest.ts
- src/reconciliation/query.ts
- src/server/server.ts
- test/fixtures/terms.ttl
- test/server/server.test.ts
* Add feature to current API repository because that’s the fastest way
to get started. Later, we may want to restructure the repositories.
* Reorganize tests to filter on query text for better assertions.
#265.
> feat: Add Reconciliation service

- CONTRIBUTING.md
- README.md
- docs/tests.md
- packages/network-of-terms-catalog/README.md
- packages/network-of-terms-graphql/README.md
- packages/network-of-terms-reconciliation/README.md
> docs: Improve explanation on how to run locally

- Dockerfile
Reduce Docker image size from 263MB to 147MB.
Fix #510.﻿
> build: Optimize Docker image size

- .eslintrc.json
- jest.config.js
- package-lock.json
- packages/network-of-terms-query/package.json
- packages/network-of-terms-query/src/distributions.ts
- packages/network-of-terms-query/src/query.ts
- packages/network-of-terms-query/test/query.test.ts
- packages/network-of-terms-reconciliation/src/query.ts
> feat: Provide dataset URI to queries

- .github/dependabot.yml
- package-lock.json
- package.json
> build: Fix multi-semantic-release pin

- jest.config.js
- packages/network-of-terms-reconciliation/src/locales/en.json
- packages/network-of-terms-reconciliation/src/locales/nl.json
- packages/network-of-terms-reconciliation/src/preview.ts
- packages/network-of-terms-reconciliation/src/server.ts
> feat: Show term source in reconciliation preview

- jest.config.js
- packages/network-of-terms-graphql/README.md
- packages/network-of-terms-graphql/src/resolvers.ts
- packages/network-of-terms-graphql/src/schema.ts
- packages/network-of-terms-graphql/test/server.test.ts
- packages/network-of-terms-query/src/server-test.ts
> feat: Return reconciliation URL with list of sources

- packages/network-of-terms-catalog/catalog/queries/search/wikidata-entities-places.rq
> fix: wd-places

- package-lock.json
- packages/network-of-terms-graphql/package.json
- packages/network-of-terms-graphql/src/server.ts
- packages/network-of-terms-reconciliation/package.json
- packages/network-of-terms-reconciliation/src/server.ts
Fix build failure with Fastify 3.29.0:
https://github.com/netwerk-digitaal-erfgoed/network-of-terms/runs/6224585854
> fix: Upgrade Fastify packages

- package-lock.json
Update rdf-terms to 1.8.2.
Fix #633.
> fix: Module tslib not found when running apps

- packages/network-of-terms-reconciliation/src/server.ts
- packages/network-of-terms-reconciliation/test/server.test.ts
This can be used in a Kubernetes readiness probe.
> feat: Add /reconcile readiness endpoint

- packages/network-of-terms-catalog/catalog/queries/search/stcn-drukkers.rq
> fix: STCN dataset selection

- jest.config.js
- packages/network-of-terms-catalog/src/catalog.ts
- packages/network-of-terms-catalog/test/catalog.test.ts
- packages/network-of-terms-catalog/test/fixtures/credentials.jsonld
- packages/network-of-terms-graphql/README.md
- packages/network-of-terms-graphql/src/resolvers.ts
- packages/network-of-terms-graphql/src/schema.ts
- packages/network-of-terms-query/src/catalog.ts
- packages/network-of-terms-query/src/server-test.ts
> feature: Expose source description

- packages/network-of-terms-catalog/catalog/datasets/aat.jsonld
> feat: Add AAT reconciliation

- jest.config.js
- packages/network-of-terms-query/src/query.ts
- packages/network-of-terms-query/src/server-test.ts
- packages/network-of-terms-query/test/query.test.ts
> fix: HTTP auth on Node 18

- packages/network-of-terms-catalog/catalog/queries/search/geonames.rq
Ref netwerk-digitaal-erfgoed/geonames-harvester#14
> feat: Use full-text search with GeoNames

- jest.config.js
- packages/network-of-terms-query/src/query.ts
> feat: Use Comunica timeout

- jest.config.js
- packages/network-of-terms-cli/src/query.ts
- packages/network-of-terms-graphql/README.md
- packages/network-of-terms-graphql/src/resolvers.ts
- packages/network-of-terms-graphql/src/schema.ts
- packages/network-of-terms-graphql/test/server.test.ts
- packages/network-of-terms-query/src/distributions.ts
- packages/network-of-terms-query/src/lookup/lookup.ts
- packages/network-of-terms-query/src/query.ts
- packages/network-of-terms-reconciliation/src/query.ts
> feat: Return response times per source

- jest.config.js
- packages/network-of-terms-catalog/src/getCatalog.ts
- packages/network-of-terms-catalog/src/index.ts
- packages/network-of-terms-catalog/test/catalog.test.ts
- packages/network-of-terms-cli/src/list.ts
- packages/network-of-terms-cli/src/query.ts
- packages/network-of-terms-graphql/README.md
- packages/network-of-terms-graphql/src/main.ts
- packages/network-of-terms-reconciliation/src/main.ts
> feat: Custom catalog

- jest.config.js
- packages/network-of-terms-reconciliation/src/data-extension.ts
- packages/network-of-terms-reconciliation/src/json-schema/data-extension-query.json
- packages/network-of-terms-reconciliation/src/manifest.ts
- packages/network-of-terms-reconciliation/src/server.ts
- packages/network-of-terms-reconciliation/test/server.test.ts
> feat: Support Reconciliation Data Extension

- jest.config.js
- package-lock.json
- packages/network-of-terms-reconciliation/package.json
- packages/network-of-terms-reconciliation/src/config.ts
- packages/network-of-terms-reconciliation/src/main.ts
- packages/network-of-terms-reconciliation/src/server.ts
- packages/network-of-terms-reconciliation/test/server.test.ts
And default to `false`.
Ref #942
> feat: Configure trusted proxy from env var

- README.md
> docs: Reference run options from main readme

- docker-compose.yml
- docs/docker.md
Only added the user param to docker-compose and reformat the docker.md
> Added 'user' parameter

- docker-compose.yml
> test: Fix tests when run in Docker container

- docker-compose.yml
Switch from alpine to default node image to solve issue #1048
> Changed node image

- jest.config.js
- package-lock.json
- packages/network-of-terms-graphql/package.json
- packages/network-of-terms-graphql/src/server.ts
> feat: Log GraphQL queries

- packages/network-of-terms-graphql/package.json
- packages/network-of-terms-reconciliation/package.json
Fix for package.json for graphql and reconcilation API to solve problems in Windows environment, see issue https://github.com/netwerk-digitaal-erfgoed/network-of-terms-tutorial/issues/1
> Package.json fix

- jest.config.js
- packages/network-of-terms-catalog/src/index.ts
- packages/network-of-terms-graphql/src/main.ts
- packages/network-of-terms-graphql/src/server.ts
- packages/network-of-terms-query/src/distributions.ts
- packages/network-of-terms-query/src/index.ts
- packages/network-of-terms-query/src/lookup/lookup.ts
- packages/network-of-terms-query/src/query.ts
- packages/network-of-terms-query/src/server-test.ts
- packages/network-of-terms-reconciliation/src/main.ts
- packages/network-of-terms-reconciliation/src/preview.ts
- packages/network-of-terms-reconciliation/src/query.ts
- packages/network-of-terms-reconciliation/src/server.ts
- tsconfig.build.json
Add file extension to relative imports as recommended in
https://www.typescriptlang.org/docs/handbook/esm-node.html
netwerk-digitaal-erfgoed/network-of-terms-tutorial#2
> fix: Compatibility with ESM on Node 20

- packages/network-of-terms-catalog/catalog/datasets/brabantse-gebouwen.jsonld
> fix: Update Brabantse gebouwen URI prefix

- packages/network-of-terms-catalog/catalog/queries/search/goudatijdmachine-straten.rq
ongebruikte ?identifier verwijderd
> uitbreiding scopenote met vernoeming

- jest.config.js
- packages/network-of-terms-graphql/src/resolvers.ts
- packages/network-of-terms-graphql/src/schema.ts
- packages/network-of-terms-graphql/test/server.test.ts
* Start by copying the value of scopeNote.
* Document in the GraphQL API that the value of scopeNote may change
later.
Ref #1166
> feat: Add term definition

- packages/network-of-terms-catalog/catalog/queries/search/goudatijdmachine-straten.rq
> change to always get PIDs for search results in GTM search

- packages/network-of-terms-catalog/catalog/datasets/ied.jsonld
- packages/network-of-terms-catalog/catalog/queries/lookup/ied.rq
- packages/network-of-terms-catalog/catalog/queries/search/ied.rq
Replace poolparty.rq with ied.rq to exclude technical lists from search and lookup
> Add ied.rq queries

- package-lock.json
- packages/network-of-terms-query/package.json
- packages/network-of-terms-query/src/config.ts
- packages/network-of-terms-query/src/query.ts
> feat: Introduce config object to wrap env var lookups

- packages/network-of-terms-reconciliation/README.md
> docs: Update reconciliation readme

- packages/network-of-terms-graphql/README.md
- packages/network-of-terms-graphql/src/resolvers.ts
- packages/network-of-terms-graphql/src/schema.ts
- packages/network-of-terms-graphql/test/server.test.ts
> fix: Rename description to definition

- packages/network-of-terms-catalog/catalog/datasets/muziekschatten-klassieke-werken.jsonld
- packages/network-of-terms-catalog/catalog/datasets/muziekschatten-onderwerpen.jsonld
- packages/network-of-terms-catalog/catalog/datasets/uitvoeringsmedium.jsonld
Asked by data owner to change the `mainEntityOfPage` for these three datasets
> Change ainEntityOfPage for Muziekschatten and Uitvoeringsmedium

- packages/network-of-terms-catalog/catalog/queries/lookup/rijksmonumenten.rq
- packages/network-of-terms-catalog/catalog/queries/search/rijksmonumenten.rq
> fix: Make Rijksmonumenten name optional

- jest.config.js
- packages/network-of-terms-catalog/catalog/datasets/aat-materials.jsonld
- packages/network-of-terms-catalog/catalog/datasets/aat-processes-and-techniques.jsonld
- packages/network-of-terms-catalog/catalog/datasets/aat-styles-and-periods.jsonld
- packages/network-of-terms-catalog/catalog/datasets/aat.jsonld
- packages/network-of-terms-catalog/catalog/datasets/eurovoc.jsonld
- packages/network-of-terms-catalog/catalog/datasets/rkdartists.jsonld
- packages/network-of-terms-catalog/catalog/datasets/uitvoeringsmedium.jsonld
- packages/network-of-terms-catalog/catalog/datasets/wikidata-entities-all.jsonld
- packages/network-of-terms-catalog/catalog/datasets/wikidata-entities-persons.jsonld
- packages/network-of-terms-catalog/catalog/datasets/wikidata-entities-places.jsonld
- packages/network-of-terms-catalog/catalog/datasets/wikidata-entities-streets.jsonld
- packages/network-of-terms-catalog/src/getCatalog.ts
- packages/network-of-terms-catalog/test/catalog.test.ts
- packages/network-of-terms-graphql/src/resolvers.ts
- packages/network-of-terms-graphql/test/server.test.ts
- packages/network-of-terms-query/src/catalog.ts
- packages/network-of-terms-query/src/server-test.ts
> chore: Declare multiple dataset languages

- packages/network-of-terms-catalog/catalog/datasets/abr.jsonld
> fix: ABR SPARQL URL

- packages/network-of-terms-catalog/catalog/datasets/brinkman.jsonld
- packages/network-of-terms-catalog/catalog/datasets/nta.jsonld
- packages/network-of-terms-catalog/catalog/datasets/stcn-drukkers.jsonld
Next PR will contain the new SPARQL endpoint of the KB linked data
> Temporary endpoint change to IP adress old environment

- jest.config.js
- packages/network-of-terms-graphql/src/resolvers.ts
- packages/network-of-terms-graphql/src/schema.ts
- packages/network-of-terms-graphql/test/server.test.ts
> feat: Support multilingual lookup

- jest.config.js
- packages/network-of-terms-catalog/src/genre.ts
> fix: Make fetching genres more resilient

- packages/network-of-terms-catalog/catalog/datasets/geonames-nl-be-de.jsonld
> feat: All global GeoNames source

- packages/network-of-terms-catalog/catalog/datasets/westerbork.jsonld
> fix: description westerbork
